apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
images:
  - name: REPLACE_ME_IMAGE
    newName: REPLACE_ME_IMAGE
    newTag: REPLACE_ME_TAG
